name: Build Android

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubunt-latest

        container:
          image: docker.io/cypress/browsers

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup node js
              uses: actions/setup-node@v4     
              with:
                node-version: 14
                
            - uses: mobile-dev-inc/action-maestro-cloud@v1.1.0
              with:
                  api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
                  app-file: qafood.apk             